FROM python:3.9.13-alpine3.16

RUN apk update
RUN apk add git
    
#RUN git clone https://github.com/databricks-academy/data-engi.netneering-with-databricks.git

#Entry point is /bin/sh

#/data-engineering-with-databricks